### ISSUE TITLE
Is there a way to limit addresses which can send udp packets?

### ISSUE THREAD

**Issue by deltaskelta** [statsd/statsd#601]
It seems like the default is that it listens for udp packets from anywhere...I don't see anything in the settings to limit where the packets come from.

Is there a way to do this?

**Comment by juneidysoo** [comment]
There is no settings for that yet. But I believe it is possible and not too difficult because node.js gives the `rinfo` of every packets it received.

**Comment by BlueHatbRit** [comment]
Apologies for the notifications on an old issue. Now this project has been revivied, I'm trying to work through existing issues and PR's.

I think this is a problem best solved by something like iptables or another firewall. We wouldn't want to bloat the module if you can achieve this with something that's standard on most operation systems and machines. Also, we'd still have to look at the UDP requests coming in, so we'd be accepting the request in some way and then just rejecting the stats, that wouldn't defend you from any sort of ddos.

Using iptables (or similar) you can lock down to only letting specific IP's through to a port, this should achieve what you're after I think.

If not, then I suggest we move discussion to #636 and re-open that if needed since it has a bit more detail on it.

Thanks for the suggestion though!
