### ISSUE TITLE
Which statsd project is now the standard?

### ISSUE THREAD

**Issue by mcandre** [statsd/statsd#618]
* etsy/statsd appears to be no longer maintained, based on the git commit activity drop-off.
* https://github.com/johndodev/etsy-statsd responds with a 404 http status
* Multiple projects now feature unofficial extensions to statsd, which make many collectors fail with parse errors.

Can we unify statsd once again?

**Comment by claudio-benfatto** [comment]
It's a good question. Would be nice to keep this project alive, given the number of people who have an interest in it. 
Or at least create a valid alternative...

**Comment by ricardobeat** [comment]
cc @mrtazz ?

**Comment by johndodev** [comment]
I deleted mine because I could use this one with influxDb.

Moreover, influxDb have lauched telegraf as colloctor, which can replace statsd (and even have a plugin to listen statsd input, so no need to change any app code).

If you use one of their supported ouput plugin (like influxDb, or graphinte,..) you can replace statsd with telegraf. 

https://docs.influxdata.com/telegraf/v1.3/introduction/getting_started/

**Comment by mrtazz** [comment]
closing in favour of https://github.com/statsd/statsd/issues/649
