### ISSUE TITLE
Create 'official' Docker Hub image

### ISSUE THREAD

**Issue by pataquets** [statsd/statsd#628]
As requested on PR #573.
Having a canonical, public Docker image on Docker Hub automatically built from source for maximum trustiness would add another distribution/deployment method and ease installation.
There are people with clones of this git repo tracking changes that need pull upstream->merge->push to keep automated builds up-to-date and causing lots of duplicate efforts.
See original PR for more info and reasoning.

**Comment by CpuID** [comment]
+1

**Comment by aniljaiswal** [comment]
+1

**Comment by pataquets** [comment]
@pathzzrd : ping?

**Comment by pataquets** [comment]
@pathzzrd Any feeedback on this? Looks like the issue got some interest, judging by its +1's ;)
cc: @benburry

**Comment by gbahrani** [comment]
+1

**Comment by CpuID** [comment]
*bump*

**Comment by BlueHatbRit** [comment]
This has been done, huzzar! With the project being revived, this was one of the first things I did. It's being auto-built on new master tags - https://hub.docker.com/r/statsd/statsd.

I think we've had a few people using it but it would be great to get some feedback, and if anyone wants to contribute a markdown document with instructions for using it, that would be amazing!

Closing this since it's been implemented, but please drop feedback in here or on the gitter channel.
