### ISSUE TITLE
Blacklist an IP on StatsD Daemon

### ISSUE THREAD

**Issue by abhinav-agrawal** [statsd/statsd#636]
Hello,

Is it possible to blacklist an IP so that it cannot send data to StatsD Daemon ?
We have an IP which is sending an enormous amount of data which makes our system unstable. I want to know if there is a way to block it.

If not, could you incorporate such a feature ?

Thanks in advance

**Comment by seapasulli** [comment]
I am not at all a member of this project but curious why iptables isn't a possible solution in the mean time?

**Comment by juneidysoo** [comment]
Related to #601?

**Comment by BlueHatbRit** [comment]
Working through some older issues, I'm sorry this has been left for so long. The project has only recently been revived.

As suggested by lookcrabs, this is something you can achieve with something like iptables or some other firewall on the machine itself. If you want to block malicious or aggressive stat publishing then I'd suggest you probably want to lock your server down a little more than just at the statsd level.

Unless someone can come up with a reason why this should be done by statsd rather than using something like a firewall, I'm going to close this. Very happy to revive discussion if someone thinks I'm wrong 😄
