### ISSUE TITLE
eval to read config file

### ISSUE THREAD

**Issue by Nanofortress** [statsd/statsd#650]
On statsd/lib/config.js in line 19 we have this piece of code to set config to the string data
```
fs.readFile(file, function (err, data) {
      if (err) { throw err; }
      old_config = self.config;

      self.config = eval('config = ' + data);  // <- Here
      self.emit('configChanged', self.config);
    });
```
Isn't this very dangerous to attacks? Someone can modify and inject piece of codes into the config file and the string inside would be evaluated without any checks.

**Comment by Nanofortress** [comment]
I think we should use JSON.parse(data) instead since it checks for the content.

**Comment by mrtazz** [comment]
I agree that json parsing would probably be a nicer approach. But in terms of risk it's up to permissions of the config file on the deployment. Because the same user can probably also just edit the js source files if they have access to the config file. Feel free to submit a PR if you're interested in changing the behaviour here but from a risk perspective I don't think this is a problem
