### ISSUE TITLE
Using micrometer-registry-statsd doesn't report TimeUnit to DataDog

### ISSUE THREAD

**Issue by ayeletmorris** [statsd/statsd#719]
Hi, I'm using micrometer-registry-statsd with @timed to report time series data to DataDog, and all of my metrics have "none" in the time unit section in the metrics summary page.

I saw that in the StatsdMeterRegistry class the "getBaseTimeUnit" method returns Milliseconds, and when I updated all my metrics manually (this took forever :) ) to milliseconds, the data in my graphs makes sense.

Why doesn't it show this reported time unit in the dataDog metric? Why isn't is sent?

BTW - I asked this question in micrometer gitHub and got this answer: https://github.com/micrometer-metrics/micrometer/issues/2528 
They say that in their implementation (DatadogMeterRegistry) they do send the time unit in the metric metadata.

Thanks for your help :)

**Comment by BlueHatbRit** [comment]
Hi @ayeletmorris, I'm sorry to send you on elsewhere but I believe the maintainer of micrometer was actually trying to point you to datadog's statsd client rather than this repo. This repo is the statsd daemon which receives and aggregates metrics, the datadog statsd client is the one which sends it onto our daemon.

Looking at micrometer, it looks like a Java project so my best guess is that you'll want the datadog statsd java client repo here https://github.com/DataDog/java-dogstatsd-client.

I hope that helps you on your journey, sorry I couldn't be more help but do come back if you think this is a problem with the receiving daemon rather than the sending client. I'll close this for now but feel free to re-open it if needed.
